version: '2'
checks:
  argument-count:
    config:
      threshold: 5
plugins:
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: 'C'
  pep8:
    enabled: true
exclude_patterns:
- tests/
- .idea/