version: '2'
checks:
  argument-count:
    config:
      threshold: 5
plugins:
  bandit:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: 'C'
exclude_patterns:
- tests/
- .idea/
- htmlcov/
- bin/__init__.py
- bin/commands/__init__.py
