language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update
  - sudo apt-get install git
install: "pip install -r requirements-test.txt"
script:
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/bin"

  # setup git
  - git --version
  - git config --global user.email "Brickstertwo@users.noreply.github.com"
  - git config --global user.name "Marcus Rosenow"

  # test
  - nosetests --with-coverage --cover-branches --cover-erase --cover-inclusive
  - coverage report --include=bin/* --omit=*/__init__.py
  - coverage xml --include=bin/* --omit=*/__init__.py -o coverage.xml

  # upload coverage report for pushes to master only
  # secure environment variables aren't available for PRs from other repositories
  - if [[ ! -z "$CODACY_PROJECT_TOKEN" ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then python-codacy-coverage -r coverage.xml; fi
