dist: xenial
language: python
python:
  - "2.7"
  - "3.9"
addons:
  apt:
    update: true
    sources:
      - 'ppa:git-core/ppa'
    packages:
      - git
before_install:
  # make sure travis can update the system git config
  - sudo chown travis:travis /etc
install: "pip install -r requirements-test.txt"
before_script:
  # install CodeClimate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

  # notify CodeClimate of this build
  - ./cc-test-reporter before-build
script:
  # set up path
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/bin"
  - export MANPATH="$MANPATH:$TRAVIS_BUILD_DIR/man"

  # set up git
  - git --version
  - git config --global user.email "Brickstertwo@users.noreply.github.com"
  - git config --global user.name "Marcus Rosenow"

  # test
  - nosetests --with-coverage --cover-branches --cover-erase --cover-inclusive --cover-package=bin --verbose --no-skip

after_script:
  # send coverage report to CodeClimate
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
