dist: trusty
language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update
  - sudo apt-get install git
  # make sure travis can update the system git config
  - sudo chown travis:travis /etc
install: "pip install -r requirements-test.txt"
script:
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/bin"

  # setup git
  - git --version
  - git config --global user.email "Brickstertwo@users.noreply.github.com"
  - git config --global user.name "Marcus Rosenow"

  # test
  - nosetests --no-skip --with-coverage --cover-branches --cover-erase --cover-inclusive --cover-package=bin --verbose
  - codeclimate-test-reporter
