dist: trusty
language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update
  - sudo apt-get install git
  # make sure travis can update the system git config
  - sudo chown travis:travis /etc
install: "pip install -r requirements-test.txt"
before_script:
  # install CodeClimate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

  # notify CodeClimate of this build
  - ./cc-test-reporter before-build
script:
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/bin"

  # setup git
  - git --version
  - git config --global user.email "Brickstertwo@users.noreply.github.com"
  - git config --global user.name "Marcus Rosenow"

  # test
  - nosetests --with-coverage --cover-branches --cover-erase --cover-inclusive --cover-package=bin --verbose --no-skip

after_script:
  # send coverage report to CodeClimate
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
