.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-UPSTREAM" "1" "August 2019" "" ""
.
.SH "NAME"
\fBgit\-upstream\fR \- get the current upstream branch
.
.SH "SYNOPSIS"
\fBgit upstream\fR [(\fB\-r\fR|\fB\-\-include\-remote\fR)] [(\fB\-R\fR|\fB\-\-no\-include\-remote\fR)]
.
.br
\~\~\~\~\~\~\~\~\~\~\~\~\~[(\fB\-b\fR|\fB\-\-branch\fR)]
.
.br
\fBgit upstream\fR (\fB\-h\fR|\fB\-\-help\fR)
.
.br
\fBgit upstream\fR (\fB\-v\fR|\fB\-\-version\fR)
.
.SH "DESCRIPTION"
\fBgit\-upstream\fR gets the current upstream branch\.
.
.SH "OPTIONS"
.
.TP
\fB\-r\fR|\fB\-\-include\-remote\fR
Print the remote name, as well\.
.
.TP
\fB\-R\fR|\fB\-\-no\-include\-remote\fR
Don\'t print the remote name\.
.
.TP
\fB\-b\fR|\fB\-\-branch\fR
The branch whose upstream should be returned\. If not specified, the current branch is used\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Print a simple help message\.
.
.TP
\fB\-v\fR|\fB\-\-version\fR
Print version\.
.
.SH "CONFIGURATION"
.
.TP
\fBgit\-upstream\.include\-remote\fR \fIbool\fR
When should remote information print\. Options (\fB\-r\fR|\fB\-\-include\-remote\fR) and (\fB\-R\fR|\fB\-\-no\-include\-remote\fR) override this value\.
.
.IP
Options are:
.
.br
\fBNEVER\fR = \'Never include remote\'
.
.br
\fBALWAYS\fR = \'Always include remote\'
.
.br
\fBNONE_LOCAL\fR = \'Only include when not a local remote\'
.
.br
.
.IP
Default: \fINEVER\fR
.
.SH "SEE ALSO"
git\-config(1)
