.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-CHANGES" "1" "March 2016" "" ""
.
.SH "NAME"
\fBgit\-changes\fR \- lists the commits between this branch and another
.
.SH "SYNOPSIS"
\fBgit changes view\fR [(\fB\-b\fR|\fB\-\-branch\fR) \fIbranch\fR] [(\fB\-c\fR|\fB\-\-count\fR)] [(\fB\-s\fR|\fB\-\-stat\fR)]
.
.br
\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~[(\fB\-d\fR|\fB\-\-diff\fR)] [\fB\-\-color\fR [\fIwhen\fR]] [\fB\-\-no\-color\fR]
.
.br
\fBgit changes associate\fR [(\fB\-q\fR|\fB\-\-quiet\fR)] [\fIbranch\fR]
.
.br
\fBgit changes unassociate\fR [(\fB\-a\fR|\fB\-\-all\fR)] [(\fB\-p\fR|\fB\-\-prune\fR)] [(\fB\-q\fR|\fB\-\-quiet\fR)]
.
.br
\fBgit changes\fR (\fB\-h\fR|\fB\-\-help\fR)
.
.br
\fBgit changes\fR (\fB\-v\fR|\fB\-\-version\fR)
.
.SH "DESCRIPTION"
\fBgit\-changes\fR lists the commits between the current branch and another\. Changes are defined as the commits between HEAD and the merge base calculated using the current and a user specified branch\.
.
.SH "OPTIONS"
.
.TP
\fBview\fR
View changes between branches\. This is the default when no subcommand is specified\.
.
.TP
\fB\-b\fR|\fB\-\-branch\fR \fIbranch\fR
Show the commits between HEAD and \fIbranch\fR\. When not specified, the branch\'s association is used\. If no association exists, master is used\.
.
.TP
\fB\-c\fR|\fB\-\-count\fR
Show as a count of changes\.
.
.TP
\fB\-s\fR|\fB\-\-stat\fR
Show as a diffstat\.
.
.TP
\fB\-d\fR|\fB\-\-diff\fR
Show as a full diff\.
.
.TP
\fB\-\-color\fR [\fIwhen\fR]
Show colored output\. \fIwhen\fR must be one of \fBalways\fR, \fBnever\fR, or \fBauto\fR\. Not including \fIwhen\fR is equivalent to \fB\-\-color=always\fR\.
.
.TP
\fB\-\-no\-color\fR
Never color output\. Same as \fB\-\-color=never\fR\.

.
.TP
\fBassociate\fR
View/update the current association\.
.
.TP
\fINone\fR
Print the current association\.
.
.TP
\fIbranch\fR
Associate the current branch with another\. Once associated, \fB\-b\fR|\fB\-\-branch\fR can be omitted when using \fBview\fR and the association will be used\.
.
.TP
\fB\-q\fR|\fB\-\-quiet\fR
Suppress all non\-error output\. Cannot be used without \fIbranch\fR\.

.
.TP
\fBunassociate\fR
Remove associations\.
.
.TP
\fINone\fR
Unassociate the current branch\.
.
.TP
\fB\-a\fR|\fB\-\-all\fR
Unassociate all branches\.
.
.TP
\fB\-p\fR|\fB\-\-prune\fR
Unassociate branches that no longer exist\.
.
.TP
\fB\-q\fR|\fB\-\-quiet\fR
Suppress all non\-error output\.

.
.TP
\fB\-h\fR|\fB\-\-help\fR
Print a simple help message\.
.
.TP
\fB\-v\fR|\fB\-\-version\fR
Print version\.
.
.SH "CONFIGURATION"
.
.TP
\fBgit\-changes\.default\-branch\fR \fIstring\fR
The default branch to use when finding changes\. Option (\fB\-b\fR|\fB\-\-branch\fR) \fIbranch\fR overrides this setting\.
.
.IP
Default: \fImaster\fR
.
.TP
\fBgit\-changes\.associations\.*\fR \fIstring\fR
Defines an association between the branch in the key and the value\. Under normal circumstances, these entries are created/removed automatically\.
.
.IP
Default: \fImaster\fR
.
.SH "SEE ALSO"
git\-diff(1), git\-log(1)
