.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SETTINGS" "1" "December 2014" "" ""
.
.SH "NAME"
\fBgit\-settings\fR \- more ways to view and edit config files
.
.SH "SYNOPSIS"
\fBgit\-settings\fR [(\fB\-h\fR|\fB\-\-help\fR)]
.
.br
\fBgit\-settings\fR [(\fB\-\-local\fR|\fB\-\-global\fR|\fB\-\-system\fR)] \fB\-\-destroy\-section\fR \fIsection\fR
.
.br
\fBgit\-settings\fR [(\fB\-\-local\fR|\fB\-\-global\fR|\fB\-\-system\fR)] \fB\-\-print\-section\fR \fIsection\fR
.
.SH "DESCRIPTION"
\fBgit\-settings\fR is a compliment to \fBgit\-config\fR that adds missing functionality\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-destory\-section\fR \fIsection\fR
Destory a section from the local, global, and system config files\.
.
.TP
\fB\-\-print\-section\fR \fIsection\fR
Print a section from the local, global, and system config files\. Optionally, a specific configation can be specified and only the section present in that file will be printed\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Display git\-settings man page\.

