.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-ABANDON" "1" "June 2015" "" ""
.
.SH "NAME"
\fBgit\-abandon\fR \- drop a count or range of stashes
.
.SH "SYNOPSIS"
\fBgit abandon\fR [(\fB\-d\fR|\fB\-\-dry\-run\fR)] [\fIstart\fR] \fIend\fR
.
.br
\fBgit abandon\fR (\fB\-h\fR|\fB\-\-help\fR)
.
.br
\fBgit abandon\fR (\fB\-v\fR|\fB\-\-version\fR)
.
.SH "DESCRIPTION"
\fBgit\-abandon\fR is a shortcut for when you need to drop some, but not all, stashes\. Stashes can be dropped using a count or a range\. If you want to drop all your stashes, just use \fBgit stash clear\fR\.
.
.SH "OPTIONS"
.
.TP
\fIstart\fR
An optional start (inclusive) of the range of stashes to drop\. If not specified, zero (0) will be used\.
.
.TP
\fIend\fR
The end (exclusive) of the range of stashes to drop\.
.
.TP
\fB\-d\fR|\fB\-\-dry\-run\fR
Print the stashes that would be dropped but don\'t drop them\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Print a simple help message\.
.
.TP
\fB\-v\fR|\fB\-\-version\fR
Print version\.
.
.SH "SEE ALSO"
git\-stash(1) \fIhttp://git\-scm\.com/docs/git\-stash\fR
