.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SNAPSHOT" "1" "November 2014" "" ""
.
.SH "NAME"
\fBgit\-snapshot\fR \- create a snapshot of the changes in a dirty working directory
.
.SH "SYNOPSIS"
\fBgit snapshot\fR [(\fB\-m\fR|\fB\-\-message\fR) \fImessage\fR]
.
.br
\fBgit snapshot\fR [(\fB\-h\fR|\fB\-\-help\fR)]
.
.br
\fBgit snapshot list\fR
.
.br
\fBgit snapshot clear\fR
.
.br
\fBgit snapshot drop\fR \fIsnapshot\fR
.
.br
\fBgit snapshot apply\fR \fIsnapshot\fR
.
.br
\fBgit snapshot pop\fR \fIsnapshot\fR
.
.SH "DESCRIPTION"
Used to record the current state of the working directory without reverting it\. The snapshot is stored using git stash prepended with snapshot@{i} to differentiate it and stashes created normally\.
.
.SH "OPTIONS"
.
.TP
\fB\-m\fR|\fB\-\-message\fR \fImessage\fR
Message used when creating the stash entry\. This has no effect on the snapshot@{i} part of the label\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Display git\-snapshot man page\.
.
.TP
\fBlist\fR
List all snapshots\.
.
.TP
\fBclear\fR
Remove all snapshots\.
.
.TP
\fBdrop\fR \fIsnapshot\fR
Drop an individual snapshot in the form snapshot@{\fIid\fR}\.
.
.TP
\fBapply\fR \fIsnapshot\fR
Apply a snapshot in the form snapshot@{\fIid\fR}\.
.
.TP
\fBpop\fR \fIsnapshot\fR
Apply then drop a snapshot in the form snapshot@{\fIid\fR}\.

