.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-RESTASH" "1" "December 2015" "" ""
.
.SH "NAME"
\fBgit\-restash\fR \- restash changes
.
.SH "SYNOPSIS"
\fBgit restash\fR [(\fB\-q\fR|\fB\-\-quiet\fR)] [\fIstash\fR]
.
.br
\fBgit restash\fR (\fB\-h\fR|\fB\-\-help\fR)
.
.br
\fBgit restash\fR (\fB\-v\fR|\fB\-\-version\fR)
.
.SH "DESCRIPTION"
Removes the changes applied by a stash\. This is effectively a shortcut to reverse apply a stash patch:
.
.IP "" 4
.
.nf

git stash show \-\-patch | git apply \-\-reverse
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fIstash\fR
The stash whose patch should be reverse applied\. If not supplied, the latest stash will be used\.
.
.TP
\fB\-q\fR|\fB\-\-quiet\fR
Suppress all non\-error output\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Print a simple help message\.
.
.TP
\fB\-v\fR|\fB\-\-version\fR
Print the current version\.
.
.SH "SEE ALSO"
git\-stash(1), git\-apply(1)
