.\" Manpage for git-snapshot.
.TH man 1 "2014-10-12" "1.0" "git-state man page"
.SH NAME
A more concise and comprehensive version of git status, git log, and related commands in one.
.SH SYNOPSIS
git state
.SH DESCRIPTION
Use git state to view the current state of the working directory. The output includes results from git status, git log, and git branch.
.SH AUTHOR
Marcus Rosenow
