.\" Manpage for git-snapshot.
.TH man 1 "2014-10-12" "1.0" "git-state man page"
.SH NAME
git-state - View the state of the working tree
.SH SYNOPSIS
git state [-h]
.SH DESCRIPTION
Used to see a more concise and comprehensive view of the working directory. The output includes results from git status, git log, git branch, and git stash.
.SH OPTIONS
.PP 
\-h
.RS 4
Display git-state man page.
.RE
.SH AUTHOR
Marcus Rosenow
