.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-CHANGES" "1" "December 2014" "" ""
.
.SH "NAME"
\fBgit\-changes\fR \- lists the commits between this branch and another
.
.SH "SYNOPSIS"
\fBgit changes\fR [(\fB\-b\fR|\fB\-\-branch\fR) \fIbranch\fR] [(\fB\-c\fR|\fB\-\-count\fR)] [(\fB\-h\fR|\fB\-\-help\fR)]
.
.SH "DESCRIPTION"
\fBgit\-changes\fR lists the commits between the current branch and another\. Changes are defined as the commits between HEAD and the merge base calculated using the current and a user specified branch\.
.
.SH "OPTIONS"
.
.TP
\fB\-b\fR|\fB\-\-branch\fR
Show the commits between HEAD and \fIbranch\fR\. When not specified, master is used\.
.
.TP
\fB\-c\fR|\fB\-\-count\fR
Prints the total changes instead of listing them\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Display git\-changes man page\.
.
.SH "CONFIGURATION"
.
.TP
\fBgit\-settings\.default\-branch\fR \fIstring\fR
The default branch to use when finding changes\. Option (\fB\-b\fR|\fB\-\-branch\fR) \fIbranch\fR overrides this setting\.
.
.IP
Default: master

