.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SETTINGS" "1" "June 2015" "" ""
.
.SH "NAME"
\fBgit\-settings\fR \- more ways to view and edit config files
.
.SH "SYNOPSIS"
\fBgit settings get\fR [\fIfile\-option\fR] [(\fB\-d\fR|\fB\-\-default\fR) \fIvalue\fR] \fIkey\fR
.
.br
\fBgit settings destroy\fR [(\fB\-d\fR|\fB\-\-dry\-run\fR)] \fIsection\fR
.
.br
\fBgit settings list\fR [\fIfile\-option\fR] [(\fB\-p\fR|\fB\-\-pretty\fR)] [(\fB\-f\fR|\fB\-\-format\fR) \fIformat\fR] [(\fB\-c\fR|\fB\-\-count\fR)] [\fIsection\fR]
.
.br
\fBgit settings\fR (\fB\-h\fR|\fB\-\-help\fR)
.
.br
\fBgit settings\fR (\fB\-v\fR|\fB\-\-version\fR)
.
.SH "DESCRIPTION"
\fBgit\-settings\fR is a compliment to \fBgit\-config\fR that adds missing functionality\.
.
.SH "OPTIONS"
.
.TP
\fBget\fR \fIkey\fR
Retrieve a configuration by key\.
.
.TP
\fB\-d\fR|\fB\-\-default\fR
A default value to use when no configuration exists\.
.
.TP
\fIfile\-option\fR
The key will be loaded from a specific file\. See "\fBFILE OPTIONS\fR" section for more details\.

.
.TP
\fBdestroy\fR \fIsection\fR
Destroy a section from the local, global, and system config files\.
.
.TP
\fB\-d\fR|\fB\-\-dry\-run\fR
Don\'t destroy anything but show which configurations would be removed\.

.
.TP
\fBlist\fR
List all configuration settings respecting override precedence\. If any options are specified, \fBlist\fR switches to section mode\.
.
.TP
\fIsection\fR
Limit the output to a given section\.
.
.TP
\fIfile\-option\fR
Limits the section values to a specific file\. See "\fBFILE OPTIONS\fR" section for more details\.
.
.TP
\fB\-p\fR|\fB\-\-pretty\fR
The section is printed in config file format\.
.
.TP
\fB\-f\fR|\fB\-\-format\fR \fIformat\fR
The section is printed in the specified format\. Valid values include: \fIcompact\fR and \fIpretty\fR\.
.
.TP
\fB\-c\fR|\fB\-\-count\fR
The count of keys in a given section is printed rather than the section itself\.

.
.TP
\fB\-h\fR|\fB\-\-help\fR
Print a simple help message\.
.
.TP
\fB\-v\fR|\fB\-\-version\fR
Print version\.
.
.SH "FILE OPTIONS"
Some subcommands can be limited to a specific file\. The valid options are:
.
.TP
\fB\-\-local\fR
Use local config file\.
.
.TP
\fB\-\-global\fR
Use global config file\.
.
.TP
\fB\-\-system\fR
Use system config file\.
.
.TP
\fB\-\-file\fR \fIfile\fR
Use a specific config file\.
.
.SH "CONFIGURATION"
.
.TP
\fBgit\-settings\.list\.format\fR \fIstring\fR
The default formatting for git\-setting list\. Valid options include: \fBpretty\fR and \fBcompact\fR\. If no value is specified or an invalid value is entered, compact is used\. The option \fB\-p\fR|\fB\-\-pretty\fR will override this setting\.
.
.IP
Default: \fIcompact\fR

