.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-STATE" "1" "December 2014" "" ""
.
.SH "NAME"
\fBgit\-state\fR \- View the state of the working tree
.
.SH "SYNOPSIS"
\fBgit state\fR [(\fB\-l\fR|\fB\-\-log\fR) \fIcount\fR] [(\fB\-L\fR|\fB\-\-no\-log\fR)] [\fB\-\-full\-log\fR] [(\fB\-r\fR|\fB\-\-reflog\fR) \fIcount\fR] [(\fB\-R\fR|\fB\-\-no\-reflog\fR)] [\fB\-\-full\-reflog\fR] [(\fB\-s\fR|\fB\-\-status\fR)] [(\fB\-S\fR|\fB\-\-no\-status\fR)] [(\fB\-b\fR|\fB\-\-branches\fR)] [(\fB\-B\fR|\fB\-\-no\-branches\fR)] [(\fB\-t\fR|\fB\-\-stashes\fR)] [(\fB\-T\fR|\fB\-\-no\-stashes\fR)] [(\fB\-e\fR|\fB\-\-show\-empty\fR)] [(\fB\-E\fR|\fB\-\-no\-show\-empty\fR)] [(\fB\-c\fR|\fB\-\-color\fR)] [(\fB\-C\fR|\fB\-\-no\-color\fR)] [(\fB\-p\fR|\fB\-\-pretty\fR)] [(\fB\-f\fR|\fB\-\-foramt\fR) \fIformat\fR]
.
.br
\fBgit state\fR [(\fB\-h\fR|\fB\-\-help\fR)]
.
.SH "DESCRIPTION"
Used to see a more concise and comprehensive view of the working directory\. The output includes results from git status, git log, git branch, and git stash\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Display git\-state man page\.
.
.TP
\fB\-l\fR|\fB\-\-log\fR \fIcount\fR
Limits commits in the log section\. If less than 1, the section is skipped\.
.
.TP
\fB\-L\fR|\fB\-\-no\-log\fR
Don\'t output the log section\. Equivalent to \fB\-l\fR 0 or \fB\-\-log\fR 0\.
.
.TP
\fB\-\-full\-log\fR
Output the entire log regardless of size\.
.
.TP
\fB\-r\fR|\fB\-\-reflog\fR \fIcount\fR
Limits actions in the reflog section\. If less than 1, the section is skipped\.
.
.TP
\fB\-R\fR|\fB\-\-no\-reflog\fR
Don\'t output the reflog section\. Equivalent to \fB\-r\fR 0 or \fB\-\-reflog\fR 0\.
.
.TP
\fB\-\-full\-reflog\fR
Output the entire reflog regardless of size\.
.
.TP
\fB\-s\fR|\fB\-\-status\fR
Print the status section\.
.
.TP
\fB\-S\fR|\fB\-\-no\-status\fR
Don\'t print the status section\.
.
.TP
\fB\-b\fR|\fB\-\-branches\fR
Print the branches section\.
.
.TP
\fB\-B\fR|\fB\-\-no\-branches\fR
Don\'t print the branches section\.
.
.TP
\fB\-t\fR|\fB\-\-stashes\fR
Print the stashes section\.
.
.TP
\fB\-T\fR|\fB\-\-no\-stashes\fR
Don\'t print the stashes section\.
.
.TP
\fB\-e\fR|\fB\-\-show\-empty\fR
Show empty sections rather than omitting them\.
.
.TP
\fB\-E\fR|\fB\-\-no\-show\-empty\fR
Omit empty sections\. This does not apply to the status section\.
.
.TP
\fB\-c\fR|\fB\-\-color\fR
Always color output\.
.
.TP
\fB\-C\fR|\fB\-\-no\-color\fR
Never color output\.
.
.TP
\fB\-p\fR|\fB\-\-pretty\fR
Display in pretty format\.
.
.TP
\fB\-f\fR|\fB\-\-format\fR \fIformat\fR
The format used to print each section\. Valid values include: compact and pretty\.
.
.SH "CONFIGURATION"
.
.TP
\fBgit\-state\.log\.show\fR \fIbool\fR
True or false flag determining whether the log section should show when no other related flags are specified\.
.
.IP
Default: true
.
.TP
\fBgit\-state\.log\.count\fR \fIint\fR
The default log length\. Can be overridden using the \fB\-d\fR|\fB\-\-log\fR \fIcount\fR option\.
.
.IP
Default: 10
.
.TP
\fBgit\-state\.reflog\.show\fR \fIbool\fR
True or false flag determining whether the reflog section should show when no other related flags are specified\.
.
.IP
Default: true
.
.TP
\fBgit\-state\.log\.count\fR \fIint\fR
The default reflog length\. Can be overridden using the \fB\-r\fR|\fB\-\-reflog\fR \fIcount\fR option\.
.
.IP
Default: 5
.
.TP
\fBgit\-state\.format\fR \fIstring\fR
The default formatting for git\-state\. Valid options include: \fBpretty\fR and \fBcompact\fR\. If no value is specified or an invalid value is entered, compact is used\. The options \fB\-f\fR|\fB\-\-format\fR \fIformat\fR or \fB\-p\fR|\fB\-\-pretty\fR will override this setting\.
.
.IP
Default: compact
.
.TP
\fBgit\-state\.status\.show\fR \fIbool\fR
True or false flag determining whether the status section should show when no other related flags are specified\. Options (\fB\-s\fR|\fB\-\-status\fR) and (\fB\-S\fR|\fB\-\-no\-status\fR) override this value\.
.
.IP
Default: true
.
.TP
\fBgit\-state\.branches\.show\fR \fIbool\fR
True or false flag determining whether the branches section should show when no other related flags are specified\. Options (\fB\-b\fR|\fB\-\-branches\fR) and (\fB\-B\fR|\fB\-\-no\-branches\fR) override this value\.
.
.IP
Default: true
.
.TP
\fBgit\-state\.stashes\.show\fR \fIbool\fR
True or false flag determining whether the stashes section should show when no other related flags are specified\. Options (\fB\-t\fR|\fB\-\-stashes\fR) and (\fB\-T\fR|\fB\-\-no\-stashes\fR) override this value\.
.
.IP
Default: true
.
.TP
\fBgit\-state\.show\-empty\fR \fIbool\fR
True or false flag determining whether empty sections should be shown\. Options (\fB\-e\fR|\fB\-\-show\-empty\fR) and (\fB\-E\fR|\fB\-\-no\-show\-empty\fR) override this value\.
.
.IP
Default: false

