.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-TUCK" "1" "April 2016" "" ""
.
.SH "NAME"
\fBgit\-tuck\fR \- stash specific files
.
.SH "SYNOPSIS"
\fBgit tuck\fR [(\fB\-m\fR|\fB\-\-message\fR) \fImessage\fR] [(\fB\-q\fR|\fB\-\-quiet\fR)]
.
.br
\~\~\~\~\~\~\~\~\~[(\fB\-i\fR|\fB\-\-ignore\-deleted\fR)|(\fB\-I\fR|\fB\-\-no\-ignore\-deleted\fR)]
.
.br
\~\~\~\~\~\~\~\~\~\-\- \fIfile\fR [\fIfile\fR \.\.\.]
.
.br
\fBgit tuck\fR (\fB\-h\fR|\fB\-\-help\fR)
.
.br
\fBgit tuck\fR (\fB\-v\fR|\fB\-\-version\fR)
.
.SH "DESCRIPTION"
Used to stash specific files rather than the all\-or\-nothing style of \fBgit stash\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-m\fR|\fB\-\-message\fR \fImessage\fR
The message to use when stashing the files\.
.
.TP
\fB\-q\fR|\fB\-\-quiet\fR
Suppress all non\-error output\.
.
.TP
\fB\-i\fR|\fB\-\-ignore\-deleted\fR
Suppress warnings related to not explicitly including deleted files\.
.
.IP
Pathspec expressions won\'t match deleted files unless they are explicitly included\. If the intention is to tuck them, add absolute references to them\. If they aren\'t supposed to be included, use this flag\.
.
.TP
\fB\-I\fR|\fB\-\-no\-ignore\-deleted\fR
Show warnings related to not explicitly including deleted files\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Print a simple help message\.
.
.TP
\fB\-v\fR|\fB\-\-version\fR
Print version\.
.
.TP
\-\-
Do not interpret any more arguments as options\.
.
.TP
\fIfile\fR \.\.\.
Files to be tucked\. The files can be absolute or specified using pathspecs\.
.
.SH "EXAMPLE"
For repository:
.
.IP "" 4
.
.nf

$ git status \-\-short
M  CONTRIBUTING\.md
 M README\.md
 M config\.yml
M  file1\.txt
MM file2\.txt
 M file3\.txt
?? CHANGELOG\.md
?? file4\.md
.
.fi
.
.IP "" 0
.
.P
To stash all non\-documentation related changes:
.
.IP "" 4
.
.nf

$ git tuck \-m "non\-docs" \-\- *\.txt config\.yml file4\.md
Saved working directory and index state On master: non\-docs
HEAD is now at 5a35bd5 Initial commit
$ git status \-\-short
M  CONTRIBUTING\.md
 M README\.md
?? CHANGELOG\.md
$ git stash list
stash@{0}: On master: non\-docs
.
.fi
.
.IP "" 0
.
.SH "CONFIGURATION"
.
.TP
\fBgit\-tuck\.ignore\-deleted\fR \fIbool\fR
Whether or not to ignore deleted files by default\. Option (\fB\-i\fR|\fB\-\-ignore\-deleted\fR) overrides this setting\.
.
.IP
Default: \fIfalse\fR
.
.SH "SEE ALSO"
git\-stash(1), gitglossary(7)
