.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-UPSTREAM" "1" "March 2015" "" ""
.
.SH "NAME"
\fBgit\-upstream\fR \- get the current upstream branch
.
.SH "SYNOPSIS"
\fBgit upstream\fR [(\fB\-r\fR|\fB\-\-include\-remote\fR)] [(\fB\-R\fR|\fB\-\-no\-include\-remote\fR)]
.
.br
\fBgit upstream\fR (\fB\-h\fR|\fB\-\-help\fR)
.
.br
\fBgit upstream\fR (\fB\-v\fR|\fB\-\-version\fR)
.
.SH "DESCRIPTION"
\fBgit\-upstream\fR gets the current upstream branch\.
.
.SH "OPTIONS"
.
.TP
\fB\-r\fR|\fB\-\-include\-remote\fR
Print the remote name, as well\.
.
.TP
\fB\-R\fR|\fB\-\-no\-include\-remote\fR
Don\'t print the remote name\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Display git\-upstream man page\.
.
.TP
\fB\-v\fR|\fB\-\-version\fR
Print version\.
.
.SH "CONFIGURATION"
.
.TP
\fBgit\-upstream\.include\-remote\fR \fIbool\fR
\fItrue\fR or \fIfalse\fR flag determining whether the remote name should be printed by default\. Options (\fB\-r\fR|\fB\-\-include\-remote\fR) and (\fB\-R\fR|\fB\-\-no\-include\-remote\fR) override this value\.
.
.IP
Default: \fIfalse\fR

